### PR TITLE
Cross build to sbt 1.0 and 0.13

### PR DESCRIPTION
**Pull request by andresilva**

### CODE REVIEW

**Comment by andresilva** [comment]
Please publish a new version after this is merged.

**Comment by ocadaruma** [comment]
@andrebeat Thanks a lot for your contribution !

**Comment by ocadaruma** [comment]
@andrebeat To adopt to sbt1.0, some changes are needed.
Please check https://github.com/andrebeat/sbt-reverse-dependency/pull/1

**Comment by andresilva** [comment]
@ocadaruma Thanks. I honestly think I forgot to compile the project so I forgot those changes 😊

**Comment by ocadaruma** [comment]
LGTM

**Comment by ocadaruma** [comment]
@andrebeat I've released `sbt-reverse-dependency:0.2.0`.

**Pull request merged**
